from google.appengine.ext import ndb


class Menu(ndb.Model):
    menu_date = ndb.StringProperty()
    dining_commons = ndb.IntegerProperty()
    menu = ndb.StringProperty()
    food_items = ndb.StringProperty()

#def create_menu_entity(date, location, menu, food):
def create_menu_entity_generated_id(date, location, menu, food):
    # note: no id kwarg
    menu = Menu(menu_date=date, dining_commons=location, menu=menu, food_items=food)
    menu.put()
    # account.key will now have a key of the form: ndb.Key(Account, 71321839)
    # where the value 71321839 was generated by Datastore for us.
    return account

def get_menu_entity(menu_key):
    menu = menu_key.get()
    return menu

def update_entity_from_key(key):
    menu = key.get()
    sandy.email = 'sandy@example.co.uk'
    sandy.put()

def delete_menu_entity(menu):
    menu.key.delete()